HOST = ""
PORT = 2360

classroomIP = {
    "SM": "192.168.1.12",
    "S": "192.168.1.11",
    "CB": "192.168.1.10",
    "G": "192.168.1.17",
    "BC": "192.168.1.16",
    "HMC": "192.168.1.13",
    "CP": "192.168.1.15",
    "ICP": "192.168.1.14",
    "Zone1": "192.168.1.18",
}

fridayClassroomIP = {
    "S": "192.168.1.11",
    "HMC": "192.168.1.13",
    "CP": "192.168.1.15",
    "Zone1": "192.168.1.18",
}

rosterWithClass = {
    "Raelyn A": classroomIP["S"],
    "Apollo B": classroomIP["S"],
    "Belle E": classroomIP["S"],
    "Matthew L": classroomIP["S"],
    "Leighton L": classroomIP["S"],
    "Mia M": classroomIP["S"],
    "Mya N": classroomIP["S"],
    "Nikki T": classroomIP["S"],
    "James A": classroomIP["S"],
    "Nora G": classroomIP["S"],
    "Ryan L": classroomIP["S"],
    "Phoebe H": classroomIP["S"],
    "Daniel C": classroomIP["SM"],
    "Aeneas S": classroomIP["SM"],
    "Nicholas Y": classroomIP["SM"],
    "Noah C": classroomIP["SM"],
    "Jolin H": classroomIP["SM"],
    "Karsten L": classroomIP["SM"],
    "Jacob L": classroomIP["SM"],
    "Victoria R": classroomIP["SM"],
    "William T": classroomIP["SM"],
    "Everett H": classroomIP["CB"],
    "Jasmin H": classroomIP["CB"],
    "James M": classroomIP["CB"],
    "Elliot L": classroomIP["CB"],
    "Anna L": classroomIP["CB"],
    "Jasper L": classroomIP["CB"],
    "Andrew T": classroomIP["CB"],
    "Grace T": classroomIP["CB"],
    "Danny U": classroomIP["CB"],
    "Elyse Y": classroomIP["CB"],
    "Alison Z": classroomIP["CB"],
    "Tyler M": classroomIP["G"],
    "Silas G": classroomIP["G"],
    "Mia H": classroomIP["G"],
    "Ethan L": classroomIP["G"],
    "Lyla M": classroomIP["G"],
    "Hannah N": classroomIP["G"],
    "Aaron O": classroomIP["G"],
    "Courtney S": classroomIP["G"],
    "Ryan S": classroomIP["G"],
    "Quinn T": classroomIP["G"],
    "Addie W": classroomIP["G"],
    "Iris C": classroomIP["HMC"],
    "Cori H": classroomIP["HMC"],
    "Aaron L": classroomIP["HMC"],
    "Ari N": classroomIP["HMC"],
    "Tyler P": classroomIP["HMC"],
    "Jamie S": classroomIP["HMC"],
    "Penny S": classroomIP["HMC"],
    "Wren Y": classroomIP["HMC"],
    "Alina S": classroomIP["HMC"],
    "Liam C": classroomIP["BC"],
    "Faith G": classroomIP["BC"],
    "James H": classroomIP["BC"],
    "Jace L": classroomIP["BC"],
    "Brandon N": classroomIP["BC"],
    "Dylan S": classroomIP["BC"],
    "Phoebe T": classroomIP["BC"],
    "Tracy M": classroomIP["BC"],
    "Maren M": classroomIP["BC"],
    "Natalia M": classroomIP["BC"],
    "Zachary K": classroomIP["CP"],
    "Sadie L": classroomIP["CP"],
    "Morgan L": classroomIP["CP"],
    "Noemi N": classroomIP["CP"],
    "Gemma O": classroomIP["CP"],
    "Kelly P": classroomIP["CP"],
    "Charlie S": classroomIP["CP"],
    "Uciah T": classroomIP["CP"],
    "Cody Y": classroomIP["CP"],
    "Lillian G": classroomIP["ICP"],
    "Olivia H": classroomIP["ICP"],
    "Riley L": classroomIP["ICP"],
    "Everleigh S": classroomIP["ICP"],

}
